name: "Build"
on:
  pull_request:
  push:
jobs:
  build-engine:
    name: Build prisma-engines 5.7.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: asterismono
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#prisma-engines_5_7_0
  build-cli:
    name: Build prisma 5.7.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: asterismono
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#prisma_5_7_0
